schema_version: 1

context:
  name: flowrep
  version: "0.5.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/flowrep-${{ version }}.tar.gz
  sha256: 812902ea6403f6bce61e61a451b4bb8067b095a4a8150f1fac69e64e2f67ddb0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }},<3.15
    - pydantic >=2.12.0,<2.13.0
    - pyiron_snippets >=1.2.1,<2.0.0

tests:
  - python:
      imports:
        - flowrep
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: flowrep - Your premier tool for workflow representations
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/flowrep/

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
    - liamhuber
